POST http://localhost:8080/api/v1/todo
content-type: application/json

{
	"task":       "Complete the todo projecct 2",
    "description": "Finish the todo application 2",
    "datetime":   "2025-02-21T15:50:00"  	
}